name: Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: 
      - ready_for_review
      - review_requested

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.code }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          code:
            - 'simple_accounting/**'

  deployment:
    name: "Deployment"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: [ '3.10' ]
    needs: paths-filter
    if: needs.paths-filter.outputs.output1 == 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Build
        run: poetry build

      - name: Set Token
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

      - name: Poetry Publish
        run: poetry publish
